# Generated by Django 3.0.5 on 2020-05-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='category',
        ),
        migrations.AddField(
            model_name='advert',
            name='category',
            field=models.ManyToManyField(to='adverts.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='url'),
        ),
    ]
