# Generated by Django 3.0.5 on 2020-05-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20200519_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageset',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='url'),
        ),
    ]
