# Generated by Django 3.0.5 on 2020-06-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='text',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.TextField(blank=True, max_length=15, null=True, verbose_name='Номер телефона'),
        ),
    ]
